language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
notifications:
  slack:
    rooms:
      - secure: npqbWDseNfOulG9m1vnxlLrDLF9tTWQf866MMXfXRl6ckQJWb081aEZi4U/MlgsfeXpFTztOVzy6uq1PnlzJFHh0UanDndpqTqmZdDyodoxZ15HkZkyoPKABUN4csUaL1aewuN0dZ5bPGD0OeL6BPKnKYsdhuIsDJTaxY5MOQaBwoHFUhs8sR6CXMVjy5xqU86NHTSto6Jx3R8DgOBk9YvCCP1JCSDqHIuy/7LhEJDl8oIPp0LjAy6U7EdyeM4ybrrkdwuC0RYPzE7DfGqkGjGrAGr70steoF+4jwPsSnJkSRdvw0zRL+kNU7fsP05ooHMtkdIye7RvaKlRE6+bF9cd85Y6oaA2MUwUyIP2FWDvga4bZZUfISC94JOoByx8dP4H82d9v9vLw4u+xEeBZcO4zxF2HSheZFhesleYbAnCp+57doj/12aMAB1o24ZaaHRlyjCWde5kDPA3PFEF4WnmVMS5O1N8dW9/XBmpHdzGPXru73Bgi7wypTyXv7z01uBxxodPmTLntQfg3h0RLsPixDjGLwe2aEyueskmGd11Kko8spdnrKZoX+N307LGik5bN6hE3DP7vQfoKdIoeVnuYOxMNSTK9yEZNyuMYVkbnAKg+VLp6Io5JiGJ7q0CRzY0i8PhPpWRoq86L6GFV9nrJa8a00+aGpHDWCej7D+0=
