language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
notifications:
  slack:
    secure: uAOyHiskJad4L46Z2eLOAb241185nu2ts4wwCwRhF8hGEFR0hqOOkbmmO7CIQHbBVMLrowbwddgQR0YQjMe/H8wQfwCXZimvT0AA6GW3/2ZowA/lrqqeGsUjJ9et/knpCRaY2gLBeT7MzLW+nvBsdeSLSDxISW0Du7GMjMzf0nAl6YSHQyS1HO8svvggNpHTmcE8s+7gSfdO9lo2iF8LDdc71AJHmnzTHkFSSpmzqmg0i9M0+abVe28zFrHOF6yQtXvReYr4SgTIwphCyFgiBvIxirnJEY8LJOSRHF+1+S1cYR8lbWxJORzo2Hkg/NkaSfqftqxwMnNdf4q4rLKxk9SCbkqTPX2sw2bszznQyibq/A5wH6jnZQnD29VNDW56VItDfhpMblL8IYNAsk7YJl45dS0ERz7tpPq3sv/gwwzVxFe0QF0EBuE+H+bGASljXWKMUU+74O+clspYql9cRB2JAItqTCWmFg66RvbeOtTuYAXK3EUOX9DT1DZ3nheXEaeEFWBqAigZwQZnzqGS8XCGbfZNpbk0sB5lCU/pkUbf+emoQPFA4TU9nMdFUM9mjhccsoaEoNpyn1WQhT5yVr/Sva0U18Wu7HFzOgIp1QmM8o4SLyOIt7JDbEB3BmTn2CNO1P/a4teT/xnP2zIRT3BIPkiKEJJOLJcYk9DO6kA=
