language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
notifications:
  slack:
    rooms:
      - secure: 0D/kv/24R7NwkR/YZWVGcnjuUFGh2jf6x9ed1SRsvRxpqRde4IL38/D3jlC9u3fwIAiUtLlmSlXVJjjtfxEenQCgwZ18CN+0eCT5Lg+XNGJHnO90s732A+UYnfLbfHpnrK85NQmQn4AmRAoDbSls24fAwq3Ze/LHHkWoW5XcmCqzsCP+RtBlhxH0GwTn0uMGoZvDoyPkABI8GJQjSBrL5KRDaSbZNGmOL8gGc8M20jbiN7ZTXnQuwsrhykA/9ZAJT3IdvbF9xkqFua5D5mDtQOOcviQqPp0hToTscNHTXaPYuw+zVWB0Ij9nIRV2B5Sw2DdMg0KkuavfEMHzl5PiqsyaHJpLrW5LX1hGrErNcDuKiqdDiKV6Wx22JJe/yxP4F3kVx1ZdHqt/fpDEG7K2Cm31AJozByaCS96Zc9iQc70km5q+zYkf7FHNdlYyV658WxI3St9rBMLz3ibK6wsfsVbrZF2sQp9tiAC1DWCLH+dlajfDNuk8gGd2hGvxj/ilwNsG0WZZ1S8UGU970tBJWlTreNDMIQi6Fh9dh0ldC76BLe8HIZdP4gKUcFwr6zxXktNoafN7YUjhVOR1rlnWMrqlKlK7F265uDGgGiZcSwAkX2jfjiqkC/FhmECzLja6+8Gnsdjmzb7YdjGCp5uzsP36gSwcYEHEGpvhqmE4Rmg=
