language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
notifications:
  slack:
    secure: cocznx+dFG8lGHRsQKDeuYxDx+gKr0g0XkA0pg263Mx9AGOlkBlDJ15oILTEBDixGcqz66i5V2iC6px7AgQc8/p/asq2J3S/CznEtZ+TXqMdevrRSj3M8G7zuHZhgw4OfPmF2s9u41VEgYVic0K+RZYeaDez6oyUo0GPJ6gONs0H2M6pY/0nE47UMDkRWOj7b+t1TbQn8PFS2u8Gr0XAYJ1PfTxktdezSnu82oY0DIjPAbqZyVg0njmE3Ig57SAAivz+wTVYtkdIlYovERArdvhtnt9FRIH5D2xZFCbAxRy7WZCLheclS/m5awkgO+pdXEQLGHHguyshZJ+8DMzx/5dUstsTL6HrT56RiYntH2E14TjeO0qOSRMjJLcNlRHPVH70NY7bfVhkAw+TUOHwlp0wFIFQBqXxgF97mCQD/dawgv99XSMEP0rfHxowEsmBJFJeHwy+Jp3wecTQrAcL0kmL7KPabBopVUAFdMWce4+I5YPY4IqYAiKQAxXnrCHPy3xUC6WA6t9FGMw/jEMTcLT5XtsqqOrAyGxMTdu6+7GxIR5SCmj7iZ9E/L1rgdFHK3NaXYmgISCyKpVetfANjboNb9Nn+Gjs+xyJtIXjG4eistNv5ZHT2/+w52MYeVl+4xPeVILLpelrBOHOqyivlxo0lOCPXP2dKZbb7BU709g=
