language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
notifications:
  slack:
    secure: m8tdGRKGFHcTqHFZ3Mkx2v5SOFhaEYeg0+e5iMYAplNly00GLNZ3m60z0p/XnQjJwGx1iHBXxoLFjYXduW5K5lJYwSaED8asqHkroAT3Z7xaMhdn9a6X3O05t1NepuEYnWvTq3ZiGV+tvG5YnuJtGBDXMbHMXvdb1yuBGL+uuWOTD3xRS6fjs3P78I1cpe76I2KfnsQdHYAL8WLwh+B/TZoZYZvJoVTqn7zjZNtVtyCAFwF7ELJ9IvuGVBz+VQVJ4w/qpxM4tfJPtKealVj1mFmAMGzosFuouJ5tQIl201PrxLCYHO2rTkGWJhQfj17/OeEhi1c89F5zFv81n+2oY8gfvNawWT6JTtHwcjPSXd6iUf9kOlLVZm6v9CatoGSD9sCEHEQEGPjqwPPBG8lIZrv72sfHdPYNU2yWy0LBu+Fr4AXsb7InH72vPYbKyQiSE0p/eA2rbM3JZjHM2hTmmoiUNGT2pkQydRSimODDG9yUmSL2J/8PFq34iFqTjlmeuRGYU0fregDdDiATOTgA1wZObbHbP5avNm8ro+rwfQQ1wq/R/JkdAVQs9Pq8Ams3WK6M1+MVlRbJQpyCtvFRuTsDIKOzP84oJWKcRK6nyCkoMYg1jf9TGkvJWn376CiffjVyHjImLT8wXD49JHo5HR1BNlRlG89hkUhkb0zHqyo=
